services:
  - type: web
    name: reelstackapp
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: ReelStack
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_ROLE
        value: web
      - key: RUN_MIGRATIONS
        value: "true"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
      - key: APIFY_TOKEN
        sync: false
      - key: APIFY_ACTOR
        value: apify/instagram-scraper
      - key: APIFY_BASE_URL
        value: https://api.apify.com/v2
